/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import napakalaki.BadConsequence;
import napakalaki.TreasureKind;

/**
 *
 * @author DiegoJesús
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    /**
     * Creates new form PendingBadConsequenceView
     */
    private BadConsequence PenBCModel;

    public PendingBadConsequenceView() {
        initComponents();
    }

    public void setPendingBadConsequence(BadConsequence pbc) {
        this.PenBCModel = pbc;

        //Mostramos en cada campo, el numero de objetos (onehand, helmet, armor, shoe, bothand) que tenemos que descartar
        // para ello le pasamos por parametro BadConsequence pcb, que contiene la información del mal rollo que deberá cumplir el jugador
        
        //Visibles
        //En el caso de ser specific o numeric llamará a sus subclases correspondientes para poner el valor correcto en cada caso:
        JNumCascosVisibles.setText(pbc.PendingEspecificoVisible(TreasureKind.helmet) + "");
        JNumUnaManoVisibles.setText(pbc.PendingEspecificoVisible(TreasureKind.oneHand) + "");
        JNumDosManosVisibles.setText(pbc.PendingEspecificoVisible(TreasureKind.bothHand) + "");
        JNumArmadurasVisibles.setText(pbc.PendingEspecificoVisible(TreasureKind.armor) + "");
        JNumZapatosVisibles.setText(pbc.PendingEspecificoVisible(TreasureKind.shoe) + "");
     
        JNumVisibles.setText(pbc.PendingVisibles() + "");

        //Ocultos
        JNumCascosOcultos.setText(pbc.PendingEspecificoOculto(TreasureKind.helmet) + "");
        JNumUnaManoOcultos.setText(pbc.PendingEspecificoOculto(TreasureKind.oneHand) + "");
        JNumDosManosOcultos.setText(pbc.PendingEspecificoOculto(TreasureKind.bothHand) + "");
        JNumArmaduraOcultos.setText(pbc.PendingEspecificoOculto(TreasureKind.armor) + "");
        JNumZapatosOcultos.setText(pbc.PendingEspecificoOculto(TreasureKind.shoe) + "");

        JNumOcultos.setText(pbc.PendingOcultos() + "");

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PendingBCEnum = new javax.swing.JLabel();
        HelmetEnum = new javax.swing.JLabel();
        UnaManoEnum = new javax.swing.JLabel();
        ArmaduraEnum = new javax.swing.JLabel();
        ZapatosEnum = new javax.swing.JLabel();
        TesorosVisiblesEnum = new javax.swing.JLabel();
        CualquieraEnum = new javax.swing.JLabel();
        TesorosOcultosEnum = new javax.swing.JLabel();
        JNumCascosVisibles = new javax.swing.JLabel();
        JNumUnaManoVisibles = new javax.swing.JLabel();
        JNumArmadurasVisibles = new javax.swing.JLabel();
        JNumZapatosVisibles = new javax.swing.JLabel();
        JNumVisibles = new javax.swing.JLabel();
        ArmaduraEnum1 = new javax.swing.JLabel();
        ZapatosEnum1 = new javax.swing.JLabel();
        CualquieraEnum1 = new javax.swing.JLabel();
        JNumCascosOcultos = new javax.swing.JLabel();
        JNumArmaduraOcultos = new javax.swing.JLabel();
        JNumZapatosOcultos = new javax.swing.JLabel();
        JNumOcultos = new javax.swing.JLabel();
        HelmetEnum1 = new javax.swing.JLabel();
        DosManosEnum = new javax.swing.JLabel();
        JNumDosManosVisibles = new javax.swing.JLabel();
        DosManosEnum1 = new javax.swing.JLabel();
        JNumDosManosOcultos = new javax.swing.JLabel();
        JNumUnaManoOcultos = new javax.swing.JLabel();
        UnaManoEnum1 = new javax.swing.JLabel();

        PendingBCEnum.setText("BadConsequence Pendiente");

        HelmetEnum.setText("Casco:");

        UnaManoEnum.setText("Una Mano:");

        ArmaduraEnum.setText("Armadura:");

        ZapatosEnum.setText("Zapatos:");

        TesorosVisiblesEnum.setText("Tesoros Visibles");

        CualquieraEnum.setText("Cualquiera:");

        TesorosOcultosEnum.setText("Tesoros Ocultos");

        JNumCascosVisibles.setText("0");

        JNumUnaManoVisibles.setText("0");

        JNumArmadurasVisibles.setText("0");

        JNumZapatosVisibles.setText("0");

        JNumVisibles.setText("0");

        ArmaduraEnum1.setText("Armadura:");

        ZapatosEnum1.setText("Zapatos:");

        CualquieraEnum1.setText("Cualquiera:");

        JNumCascosOcultos.setText("0");

        JNumArmaduraOcultos.setText("0");

        JNumZapatosOcultos.setText("0");

        JNumOcultos.setText("0");

        HelmetEnum1.setText("Casco:");

        DosManosEnum.setText("Dos Manos:");

        JNumDosManosVisibles.setText("0");

        DosManosEnum1.setText("Dos Manos:");

        JNumDosManosOcultos.setText("0");

        JNumUnaManoOcultos.setText("0");

        UnaManoEnum1.setText("Una Mano:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UnaManoEnum1)
                            .addComponent(DosManosEnum1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNumUnaManoOcultos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JNumDosManosOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UnaManoEnum)
                            .addComponent(DosManosEnum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNumUnaManoVisibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JNumDosManosVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CualquieraEnum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JNumVisibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(PendingBCEnum)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(HelmetEnum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JNumCascosVisibles))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(TesorosVisiblesEnum))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(TesorosOcultosEnum))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ZapatosEnum1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JNumZapatosOcultos))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ArmaduraEnum1)
                                .addComponent(HelmetEnum1)
                                .addComponent(CualquieraEnum1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JNumCascosOcultos)
                                .addComponent(JNumArmaduraOcultos)
                                .addComponent(JNumOcultos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ZapatosEnum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JNumZapatosVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ArmaduraEnum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JNumArmadurasVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PendingBCEnum)
                .addGap(18, 18, 18)
                .addComponent(TesorosVisiblesEnum)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HelmetEnum)
                    .addComponent(JNumCascosVisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnaManoEnum)
                    .addComponent(JNumUnaManoVisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DosManosEnum)
                    .addComponent(JNumDosManosVisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArmaduraEnum)
                    .addComponent(JNumArmadurasVisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZapatosEnum)
                    .addComponent(JNumZapatosVisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CualquieraEnum)
                    .addComponent(JNumVisibles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(TesorosOcultosEnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HelmetEnum1)
                    .addComponent(JNumCascosOcultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnaManoEnum1)
                    .addComponent(JNumUnaManoOcultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DosManosEnum1)
                    .addComponent(JNumDosManosOcultos))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArmaduraEnum1)
                    .addComponent(JNumArmaduraOcultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZapatosEnum1)
                    .addComponent(JNumZapatosOcultos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CualquieraEnum1)
                    .addComponent(JNumOcultos))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArmaduraEnum;
    private javax.swing.JLabel ArmaduraEnum1;
    private javax.swing.JLabel CualquieraEnum;
    private javax.swing.JLabel CualquieraEnum1;
    private javax.swing.JLabel DosManosEnum;
    private javax.swing.JLabel DosManosEnum1;
    private javax.swing.JLabel HelmetEnum;
    private javax.swing.JLabel HelmetEnum1;
    private javax.swing.JLabel JNumArmaduraOcultos;
    private javax.swing.JLabel JNumArmadurasVisibles;
    private javax.swing.JLabel JNumCascosOcultos;
    private javax.swing.JLabel JNumCascosVisibles;
    private javax.swing.JLabel JNumDosManosOcultos;
    private javax.swing.JLabel JNumDosManosVisibles;
    private javax.swing.JLabel JNumOcultos;
    private javax.swing.JLabel JNumUnaManoOcultos;
    private javax.swing.JLabel JNumUnaManoVisibles;
    private javax.swing.JLabel JNumVisibles;
    private javax.swing.JLabel JNumZapatosOcultos;
    private javax.swing.JLabel JNumZapatosVisibles;
    private javax.swing.JLabel PendingBCEnum;
    private javax.swing.JLabel TesorosOcultosEnum;
    private javax.swing.JLabel TesorosVisiblesEnum;
    private javax.swing.JLabel UnaManoEnum;
    private javax.swing.JLabel UnaManoEnum1;
    private javax.swing.JLabel ZapatosEnum;
    private javax.swing.JLabel ZapatosEnum1;
    // End of variables declaration//GEN-END:variables
}
