/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author DiegoJesús
 */

        
import static java.awt.Color.blue;
import static java.awt.Color.red;
import napakalaki.Treasure;

public class TreasureView extends javax.swing.JPanel {

    /**
     * Creates new form TreasureView
     */
    
    private Treasure treasureModel;
    private boolean selected = false;
    
    
    public void setTreasure(Treasure t){
        
        treasureModel = t;
        
        FotoTesoro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/treasures/" + treasureModel.getName() +".jpg")));
        
    }
    
    public boolean isSelected(){
        return selected;
    }
    
    public Treasure getTreasure(){
        return treasureModel;
    }
    
    public TreasureView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FotoTesoro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        FotoTesoro.setBackground(new java.awt.Color(255, 255, 255));
        FotoTesoro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FotoTesoroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FotoTesoro, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FotoTesoro, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FotoTesoroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FotoTesoroMouseClicked
       if(selected == false){
           selected = true;
           setOpaque(true);
           setBackground(blue);
       }
       else{
           selected = false;
           setOpaque(false);
       }
       
       repaint();
    }//GEN-LAST:event_FotoTesoroMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoTesoro;
    // End of variables declaration//GEN-END:variables
}
